#!/bin/sh

#####################################################################
#                                                                   
#               Compiles Faust programs to Audio Unit       	      
#               (c) Grame 2013                           	               
#                                                                   
#####################################################################

######################################################

FAUST_DIR=/Applications/faust-0.9.58

######################################################

AU_DIR=$HOME/Library/Audio/Plug-Ins/Components

FAUST_AUSYNTH_DIR=$FAUST_DIR/architecture/AUSynth/
cd $FAUST_AUSYNTH_DIR

if [ $# -lt 1 ]
then
	echo faust dsp file not specified
	exit
fi

if [ ! -f $1 ]
then
    echo input file does not exist
    exit
fi

faust -a $FAUST_DIR/architecture/ausynth.cpp $1 -o Source/ausynth-output.cpp

FULL_FILE_NAME=$1

FILE_NAME=$(BASENAME "$FULL_FILE_NAME")
EXTENSION="${FILE_NAME##*.}"
FILE_NAME="${FILE_NAME%.*}"

if [ $# -lt 2 ]
then
	MANUFACTURER="Grame"
else
	MANUFACTURER=$2
fi

NAME=$MANUFACTURER:' '"$FILE_NAME"

if [ $# -lt 3 ]
then
	SUB_TYPE=${FILE_NAME:0:4}
else
	SUB_TYPE=$3
fi

if [ $# -lt 4 ]
then
	MANF=${MANUFACTURER:0:4}
else
	MANF=$4
fi

perl -pi -e 's/_NAME_/'"$NAME"'/g' Info.plist
perl -pi -e 's/_DESC_/'"$NAME"'/g' Info.plist
perl -pi -e 's/_STYP_/'"$SUB_TYPE"'/g'  Info.plist
perl -pi -e 's/_MANF_/'"$MANF"'/g' Info.plist 
perl -pi -e 's/_BUNDLE_ID_/'"$FILE_NAME"'/g' Info.plist 

perl -pi -e 's/_BUNDLE_NAME_/'"$FILE_NAME"'/g' English.lproj/InfoPlist.strings 
perl -pi -e 's/_BUNDLE_INFO_/'"$NAME"'/g' English.lproj/InfoPlist.strings 

perl -pi -e 's/_NAME_/'"$NAME"'/g' Source/AUSource/FaustAUSynth.r
perl -pi -e 's/_DESC_/'"$NAME"'/g' Source/AUSource/FaustAUSynth.r 

perl -pi -e 's/_STYP_/'"$SUB_TYPE"'/g' Source/AUSource/FaustAUSynthVersion.h
perl -pi -e 's/_MANF_/'"$MANF"'/g' Source/AUSource/FaustAUSynthVersion.h 

xcodebuild ARCHS="i386 x86_64" CONFIGURATION_BUILD_DIR=$HOME/Library/Audio/Plug-Ins/Components > /dev/null 2> ./build_errors.log

rm Info.plist
cp Info-template.plist Info.plist

rm English.lproj/InfoPlist.strings
cp English.lproj/InfoPlist-template.strings English.lproj/InfoPlist.strings

rm Source/AUSource/FaustAUSynth.r
cp Source/AUSource/FaustAUSynth-template.r Source/AUSource/FaustAUSynth.r

rm Source/AUSource/FaustAUSynthVersion.h
cp Source/AUSource/FaustAUSynthVersion-template.h Source/AUSource/FaustAUSynthVersion.h

if [ -d $AU_DIR/"$FILE_NAME".component/ ]
then
	rm -r  $AU_DIR/"$FILE_NAME".component/
fi
cp -r $AU_DIR/FaustAUSynth.component $AU_DIR/"$FILE_NAME".component/
rm -r $AU_DIR/FaustAUSynth.component/

echo "'$NAME'" AU generated and installed successfully 

